services:
  - type: web
    name: telegram-bitrix-advanced
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BITRIX24_WEBHOOK_URL
        sync: false
